### ISSUE TITLE
Tatoeba evaluation scripts

### ISSUE THREAD

**Issue by simran-khanuja** [google-research/xtreme#21] opened 2020-05-03 19:46 UTC
Hi! Thanks for the code.
While downloading the tatoeba dataset, it is processed and saved in the below format in _utils_preprocess.py_
![tatoeba_process](https://user-images.githubusercontent.com/24687672/80921382-acfa1180-8d93-11ea-97a0-f8281d164c73.PNG)

However, while evaluating, the data files are retrieved in the original name format in _(run_retrieval.py)_
![tatoeba_run](https://user-images.githubusercontent.com/24687672/80921410-e6cb1800-8d93-11ea-8b6e-10b2ea7811f8.PNG)

**Comment by SimranKhanuja** [comment] 2020-05-04 06:38
One more clarification - The prediction files obtained are 0-based indices of sentences in the actual label files right?

**Comment by pruksmhc** [comment] 2020-05-11 02:40
Just to add, upon checking, the files that end with "en" don't seem to have the correct sentence alignments (checking Thai-English), whereas the original "eng" ones do.

**Comment by melvinjosej** [comment] 2020-05-12 18:25
cc @JunjieHu

**Comment by SimranKhanuja** [comment] 2020-05-13 07:22
@pruksmhc that is to avoid submitting gold labels as prediction files afaik; that is why in utils_preprocess.py they sort the english files. However I am unable to reproduce tatoeba results after separately downloading gold label files

**Comment by wasiahmad** [comment] 2020-08-25 16:39
How can we compute the accuracy for Tatoeba? It seems the run_retrieval.py only generates the predictions but no evaluation score is computed.

**Comment by sebastianruder** [comment] 2020-10-04 08:49
The tasks are only intended to be evaluated on our side as part of evaluating a submission on the leaderboard. That's why `run_retrieval.py` does not compute the accuracy directly. Closing this for now.

**Closed by sebastianruder** 2020-10-04 08:49 UTC
